version: '2.12.2'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image:
      restart: always
          - MYSQL_DATABASE: 'weblog'

          - MYSQL_USER: 'root'

          - MYSQL_PASSWORD: 411481:011

        ports:

          - '3306:3306'
        expose:

          - '3306'

        volumes:
          - my-db:/var/lib/mysql

      volumes:
        my-db:
