# Generated by Django 4.1.5 on 2023-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blog_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='این مقاله را توصیه میکنم'),
        ),
    ]
