# Generated by Django 4.1.5 on 2023-02-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='blog',
        ),
    ]
